package card;

import java.util.Collections;
import java.util.Optional;
import java.util.Stack;

/**
 * This class represents different decks used throughout the game;
 * note that the underlying deck structures are typically mutated/modified in-place.
 *
 * @param <C>: The specific type of cards contained in that deck. Normally, to
 * 			   make serialization easier, we "alias" the types generated by this
 * 			   type constructor (Deck<C>) - e.g. PersonalityDeck really is
 * 			   an alias for a Deck&lt;PersonalityCard&gt;.
 * @author Team 10 - SOEN6441
 * @version 1.0
 */
public abstract class Deck<C extends Card> {

	/**
	 * The cards of the deck. This structure is mutated. Note that since we
	 * intend to call {{@link #shuffle()} on the deck, we are using a Stack
	 * for convenience instead of a Deque implementation.
	 */
	protected Stack<C> cards;
	
	/**
	 * Draws a card if the deck has any card at all.
	 * @return card
	 */
	public Optional<C> drawCard() {
		return !cards.isEmpty() ? Optional.of(cards.pop()) : Optional.empty();
	}
	
	/**
	 * Shuffles the deck.
	 */
	public void shuffle() {
		Collections.shuffle(cards);
	}
	
	/**
	 * Gets the number of cards in the deck.
	 * @return the number of cards in the deck.
	 */
	public int size() {
		return cards.size();
	}
	
	/**
	 * Puts all the cards of the applicable type (e.g. Green player cards) 
	 * in the deck and shuffles it.
	 */
	public abstract void populateDeck();
	
}
